name = "The_Environment_and_Directed_Technical_Change"
uuid = "f65fe845-10da-4a2c-bb43-cdd6b2175305"
authors = ["morganesoufflet <morganesoufflet2002@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
